services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - IMAGE_SERVICE_URL=${IMAGE_SERVICE_URL}
    env_file:
      - .env
  
  image-service:
    build: ./image-service
    ports:
      - "3001:3001"
    env_file:
      - ./image-service/.env.local